### ISSUE TITLE
Task Viewer No Longer Working

### ISSUE THREAD

**Issue by ybadragon** [c4rth/ado-task-viewer#6]
My team and I have noticed that with the latest version of VSCode (1.73.0) this extension is no longer populating the view for the task.json file, it's just empty.

**Comment by c4rth** [comment]
Hi,
Glad this extension is used. Thanks to raise the issue.
A fix is just published in the marketplace.

VSCode no longer allows loading the javascript file the way like I did.

Kind Regards

**Comment by ybadragon** [comment]
Just updated and tested, thanks for fixing it so quickly!
